import numpy
import pyaudio

AUDIO_FORMAT = pyaudio.paInt16
NUMPY_AUDIO_FORMAT = numpy.uint16

CHANNELS = 1
SAMPLE_RATE = 44100

DECODER_TIMEOUT = 1
SOCKET_TIMEOUT = 0.01

PACKET_SIZE = 1024
SERVER_PORT = 8888
MAX_JOINABLE = 4
